[startup.digital_me]
name = "bash"
protected = true #set protected to true to respawn the container if it crashed

[startup.digital_me.args.env]
HOME = "/root"
LC_ALL = "en_US.UTF-8"
LANG = "en_US.UTF-8"

[[startup.digital_me.args.nics]]
type = "default"

[startup.digital_me.args]
script = """
redis-server --daemonize yes
js_shell "j.clients.zdb.testdb_server_start_client_get() "
js_shell "j.tools.tmux.execute('js_shell \'j.servers.digitalme.start()\'')"
"""
